bcgov/digital-journeys

.github/workflows/deploy.yaml
The PR removes redundant parameters IMAGE_NAME and IMAGE_TAG from the Github workflow deploy.yaml
- Remove IMAGE_NAME and IMAGE_TAG parameters
=> Remove IMAGE_NAME and IMAGE_TAG parameters

deployment/openshift/webapi_dc.yaml
Remove IMAGE_TAG parameter from web api deployment template as well.
=> Remove IMAGE_TAG from web api deployment template

forms-flow-api/src/formsflow_api/services/employeeDataService.py, forms-flow-web/src/components/Form/Item/View.js
This pr fixes the issue with the slow employee data fetch. I missed `$` in the URL param which made it fetch data for all users.
Also, stop showing employee data fetch error on FE as this is optional and should not keep users from entering the form if don't have GUID or no data available in ODS yet (for the user).
=> fixing filter url, removing errors on FE

.github/workflows/deploy.yaml
Fix pipeline error - "No objects past to apply" . Added the trailing pipe ("|") to the "oc process" command.
Added the trailing pipe ("|") to the "oc process" command.
=> Add missing pipe at the end of oc process command

README.md, deployment/openshift/web_config.yaml, forms-flow-api/entrypoint.dev, forms-flow-api/src/formsflow_api/services/employeeDataService.py, forms-flow-web/src/formComponents/FileUpload/index.js
Fixes an issue where you couldn't re-upload a new file after removing a file that was too big. Also fixed an issue where form submissions would time out when running the app locally (CC/ @iman-jamali-fw, think this fixes the issue you experienced), and handling a user that doesn't exist in the ODS gracefully instead of producing a 500 error. 
- Added event listener to all `fileStatusRemove` elements that on click shows the file upload component again
- Added lifecycle badge to the repo (required for all BCGov repos)
- Increased # threads for running the WebAPI locally to avoid deadlock that happens when submitting the form
- Return `400` instead of `500` if you look up a user that doesn't existing in the ODS
=> DGJ-94 Fix upload of files after removing old one

forms-flow-bpm/Dockerfile.prod, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SendSubmissionToODSDelegate.java
This PR fixes an issue when rendering a PDF in dev using Playwright: it fails with a permission denied error in the /.cache folder.
It also fixes an issue where the ODS endpoint to send submissions to is constructed wrong 
- Updated Dockerfile.prod to create a /.cache folder + update permissions accordingly
- Updated ODS url to use `#` instead of `/` as a separator for the endpoint part
=> DGJ-22 Fixed cache permission issue when rendering PDF

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/ODSAccessHandler.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SendSubmissionToODSDelegate.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/services/FormSubmissionService.java
Fixed an auth issue when sending data to the ODS. Also reverted the previous url change as it was correct before.
Apparently there's two `WebClient` beans made available for use, one that will add a `Authorization` header and one for use for any external services where you want to specify the `Authorization` header.
- Changed `webClient` to `unauthenticatedWebClient ` to fix ODS authentication issue
=> DGJ-135 Fixed BPM ODS auth issue

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/TaskAssignmentListener.java, forms-flow-bpm/src/main/resources/templates/form.html
Add a `setTimeout` to wait for the page to complete rendering before triggering PDF generation. Now the generation waits for a `#formio-form-rendered` element to be inserted into the page before starting.
Should (hopefully) fix an issue in dev where the PDF is sometimes blank.
- Insert an empty `#formio-form-rendered` div after setting the form submission
- Wait for `#formio-form-rendered` before rendering
=> DGJ-135 Delay rendering of form for PDF

forms-flow-web/src/formComponents/FileUpload/index.js
Added docx + msg to allow list as default for file upload component
-Added docx + msg to allow list as default for file upload component
=> DGJ-158 Allow docx + msg files as default for file upload

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/TaskAssignmentListener.java, forms-flow-bpm/src/main/resources/processes/telework-form.bpmn
- Fixed setting of the `managerSignatureTimestamp` variable - which I believe might have caused some of the email sending issues in dev 👀 
- Moved email sending for telework form into separate tasks and added transaction boundaries to make issues show up in Camunda + not roll back any tasks that already completed on failure. Should prevent e.g. double sending of emails if you retry a failed task
-  Modified the TaskAssignmentListener to allow usage through service tasks
- Updated Telework Form bpmn to fix email sending issues
=> DGJ-72 Split email sending for telework form into separate tasks

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FileAccessHandler.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FormAccessHandler.java, forms-flow-bpm/src/main/resources/processes/telework-form.bpmn
Fixed handling of expired tokens when retrieving files for email. After a while, email sending seems to be failing with an error indicating that the access token used to retrieve it from Camunda has expired. The cause of this can be found in the FormAccessHandler / FileAccessHandler. The `FormAccessHandler` retries a request if a 404 is returned (by Form.io) as in that service this could indicate an expired token. For the file service however, a 401 is returned, so the request would not be retried with a refreshed token.
- Updated FileAccessHandler to retry the request with a refreshed access token if it fails with a 401
=> DGJ-161 Fixed handling of expired tokens when retrieving files for email

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FileAccessHandler.java
Attempt #10 to fix the 401 error that sometimes pops up when attaching a file to an email. I've not been able to reproduce this locally, hence the many tries 😓 
From the looks of it, the 401 now sometimes happens in the signed url that is generated by formio and returned by the file service. The created token embedded in the url is sometimes expired which in the end causes the 401. *I believe* the expiry time is based on the issue time of the auth token that's used to request the file, so this PR includes a fix that makes sure we generate a new token to request the file so Formio in the end will not generate a token that is expired.
- Modified `FileAccessHandler` to always use a new token when requesting a file
=> DGJ-161 Generate new auth token when fetching file for emails

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/TaskAssignmentListener.java, forms-flow-bpm/src/main/resources/processes/telework-form.bpmn
Fixed an issue where the client would receive the adm approval in the Telework form, even if no `attachment` injection was set in the Camunda modeller for that task. 
The issue was that Spring Beans are by default reused, so the `attachment` property was carried over from the other task.
Solution: Annotate the `TaskAssignmentListener` with `@Scope(value = "prototype")` to use a new instance of the class every time it is used.
Reference:
https://docs.spring.io/spring-framework/docs/3.0.0.M3/reference/html/ch04s04.html
- Added `@Scope(value = "prototype")` annotation to our listeners that use Field injections
- Added A combining parallell gateway to the Telework form to make sure both email sending tasks complete before sending the submission to the ODS
=> DGJ-161 Fixed file attachment in client email

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SendSubmissionToODSDelegate.java
Added flag to `SendSubmissionToODSDelegate` to enable debugging of ODS submission. Logs a submission payload when enabled
- Added debug flag to `SendSubmissionToODSDelegate`
=> Added debug flag for ODS sending

forms-flow-api/src/formsflow_api/models/employee_data.py
Added mapping of the ODS `postal` field to be used in the form builder. Currently, only the office postal code is being mapped, which is not what is expected.
- Added mapping employee_data mapping of the ODS `postal` field
Available fields to be mapped: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_app_telework_info
=> DGJ-202 Added mapping of postal field

deployment/openshift/camunda_dc.yaml
Try to resolve the deployment issue with CPU resource limits.
Recreate Strategy should free up resources before recreating pod(s). Hopefully this will resolve the deployment issue with CPU resource limits.
DC > Strategy: Recreate
=> Change DeploymentConfig to Recreate Strategy

deployment/openshift/camunda_dc.yaml
The CPU_LIMIT defined in camunda_dc.yaml needs to be updated to the coorect value to prevent replication controller from failing
-There was a typo in the CPU_LIMIT value. Changed CPU_LIMIT to 300m"
-Also, strategy needs to be kept as Rolling to avoid downtime while deployment in case of more than replica.
=> Fix CPU_LIMIT value and revert startegy to rolling

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/ExtractManagerGuid.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SendSubmissionToODSDelegate.java
Manager `idir` and `guid` is sent to ODS
- The `ExtractManagerGuid` listener is updated to extract manager's `idir` and `guid`. Orignal work was kindly done by @jizhaogit
- Manager's `idir` and `guid` are added to the payload that is sent to ODS.
@jizhaogit I'd appreciate it if you could review this pr since you have context on that.
=> manager idir and guid is sent to ODS

docs/forms.md, forms-flow-api/src/formsflow_api/models/employee_data.py
Adding a new field to employee data called `displayName` to properly show first and last names.
This PR fixes the issue reported in #290 . The `name` filed, coming from ODS, does not have the format that the PSA team wants, so I made a calculated one that guarantees it is always the first name followed by the last name.
=> display name was added to employee user data

forms-flow-bpm/pom-docker.xml, forms-flow-bpm/pom.xml, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/UserGroupAssignmentListener.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/services/KeycloakClientAdminService.java
This PR adds a Camunda Listener that can assign a Keycloak group to a supervisor user.
- Keycloak Admin client was added to BPM
- A Camunda listener was added to dynamically add a group to a user that is marked as a supervisor on a form
=> Keycloak Group assignment listener was added

deployment/openshift/camunda_dc.yaml, deployment/openshift/web_dc.yaml, deployment/openshift/webapi_dc.yaml
Deployments in all 3 environments are getting triggered whenever there is a change to the imagestream image. 
Image triggers need to be removed from the deployment configurations to fix this.
=> Remove image change triggers

docker-compose.yml, forms-flow-web/src/formComponents/UploadProvider/index.js
Fixes `401` error when trying to upload ADM approval attachments. Submission ID was not passed along to the file upload service, causing the error when authenticating with Formio
- Pass along submission ID to file upload service when uploading file to submission
=> DGJ-448 Fix auth issue when uploading ADM approval attachment

forms-flow-bpm/processes/telework-form.bpmn, forms-flow-bpm/src/main/resources/application.yaml
Remove finished Telework form processes from after submission. Doing this by setting "time to live" to 0 days, which means that it will be cleaned out of the DB during the first history Cleanup Batch Window after completion.
- Added history ttl to telework form bpmn
- Added historyCleanupBatchWindow (daily, 1am - 5am)
=> DGJ-416 Enable cleanup of telework form submission history

forms-flow-bpm/processes/telework-form.bpmn, forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js, forms-flow-web/src/constants/constants.js, forms-flow-web/src/containers/NavBar.jsx, forms-flow-web/src/containers/styles.scss
- Use the `manager` role to determine whether or not tasks tab should show up
- Grant `formsflow/manager` group assignment to manager when telework form has been submitted
=> DGJ-459 Use manager role to determine task tab visibility

.github/workflows/mongo_backup.yaml, deployment/openshift/databases/mongo-backup-deploy.yaml, deployment/openshift/docker-build.yml
Issue: Set up automated backups of MongoDB instance #65
Enabled automated MongoDB backups for formiodb to support accidental corruption or removal of data to recover from.
- Deployment Config up and running for all environments `Dev`, `Test`, and `Prod`
- Added a new github workflow to trigger the build and deployment of the backup MongoDB instance
- Base image is reference from `https://github.com/BCDevOps/backup-container` as suggested [here - BC DevHub for container backups](https://developer.gov.bc.ca/Backup-Container)
- The changes will be triggered on push to `automated-db-backups` branch
=> Enabled automated MongoDB backups for formiodb

forms-flow-web/src/apiManager/services/processServices.js, forms-flow-web/src/components/Form/Item/Edit.js, forms-flow-web/src/components/Form/Steps/PreviewStepper.js, forms-flow-web/src/components/Form/Steps/SaveNext.js, forms-flow-web/src/components/Form/Steps/WorkFlow.js, forms-flow-web/src/modules/processReducer.js
This PR solves two issues with the current form edit process #481 . One is, the issue with the creation of a new `form-process-mapper` entry where it should be updated instead (lack of previous data caused this). Two, the issue with form losing its process and status properties during a new form upload or when a form is updated (and not process and status).
- process reducer and service are updated to get previous form data (this was missing in my public form pr 😅 ). This prevents the creation of unnecessary `form-process-mapper` entries in the database, instead, that field will be updated appropriately.
- In case only form and not a process are updated/edited, existing process and status are kept (this was a bug in form-flow-ai even in the latest version). This prevents losing the form's …
=> form-edit-save-process-fixed

deployment/openshift/camunda_dc.yaml, deployment/openshift/web_dc.yaml, deployment/openshift/webapi_dc.yaml
Recreate image change triggers for auto deplpyments in openshift
Changed templates for camunda, web and api to rebuild imagechange triggers
=> Recreate image change triggers for automated deployments in openshift

.github/workflows/form-flow-files-backup.yaml
- Added github workflow cron trigger to backup form-flow-files PVC
- Schedule - Daily at 9am
- Source: forms-flow-files pvc
- destination: forms-flow-files-backup
=> Added daily backup trigger for forms-flow-files PVC

formio-upload/pdf-generation/generatePdf.js
Reduced the number of pds that can be generated in parallel, to avoid the service hitting its resource limits.
- Restrict number of pdfs to be generated in parallel to 3
- Recycle browser more often to reduce chance of memory leaks
=> DGJ-483 Reduce number of pds that can be generated in parallel

.github/workflows/form-flow-files-backup.yaml
Problem: There were redundant backups getting created when multiple pods running.
Fix: removed unnecessary loop
=> fix redundant backup for forms-files-flow when multiple pods

forms-flow-bpm/processes/telework-form-html-email-test.bpmn, forms-flow-bpm/processes/telework-form.bpmn, forms-flow-web/src/components/Form/Item/Submission/Success/SuccessPage.js
This PR replaces "ADM" with "ADM (or delegate)" in the Telework Agreement form. 
Changes were made in 
- Workflow files (.bpmn) that reflect changes in the workflow process.
- Approval HTML page (.js file)
- In the form major title were updated, but Only a couple of places remain, That has been updated on the Dev environment.
Changes have been applied to the form(Available in the dev environment),
Process/Flow, notification template, and approval page content will be updated using this PR.
=> Replace "ADM" with "ADM (or delegate)" in the Telework agreement form

forms-flow-web/public/index.html
This PR will force all the `<href>` tags to open in a new tab as requested in #491 
- A `<base>` tag was added to the `header` of the topmost index overwriting all the `<href>` tags to open in new tabs.
=> base html element was added to open all the link in a new tab

forms-flow-web/public/index.html, forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/View.js, forms-flow-web/src/helper/formUtils.js
This PR removes the global `<base>` tag that makes all the `<href>` tags in the app open in new tabs and instead, add that attribute (`target="_blank"`) only to form components with an `<href>` tag. #491 
- Remove the global `base` tag
- Add a form util function that read through the form components and make the links open in new tabs
- Refactored the form util functions that rely on formio object in a separate module.
=> making the form links open in a new tabs

forms-flow-web/src/styles.scss
This PR improves the contrast of the collapsible button as part of ticket #541 
- Color of the plus and minus icons was changed to white.
=> collapsible icon color was changed

forms-flow-forms/src/authentication/index.js
Fixes an issue where temporary auth tokens generated by Formio does not have the expected expiry date. Source of issue: The expiry date of the new token was calculated as a time (3600s by default) after the `iat` of the source token instead of after the current time. This can cause the new temporary token to already be expired, which would cause a 401 if used - which is the cause of the issues reported around emails with attachments sometimes failing. 
Fix: Make sure a new `iat` is generated when generating the temporary token
=> DGJ-567 Re-generate iat of formio temp tokens

formio-upload/pdf-generation/formUtils.js, formio-upload/pdf-generation/generatePdf.js
This PR will fix the issue with the date field of the generated PDF files that were rendered empty when a supervisor signed off a submission one or more days after the original employee submission.
- A function was added to remove the `mindDate` of date fields before the form object is sent to the pdf is generated.
- Formatted the generate file to look nicer :)
I tried different approaches to disable the date validation such as making those fields `readOnly`, similar to what I did on the web form, and also various ways to use formio built-in functions --in the form generation HTML, but none worked. Finally, changed the form object before it passed to the PDF generation script in Puppeteer.
=> date fields minDate validation were removed before pdf server generation

forms-flow-web/Dockerfile, forms-flow-web/Dockerfile.prod, forms-flow-web/src/helper/formUtils.js
This PR fixes two issues, One, the issue with the web app docker build in production and two, it fixed the issue in validation errors toggle on/off due to formio redraw in `convertFormLinksToOpenInNewTabs` function, which is no longer needed in v5.
- The web local docker file was updated
- The web prod docker file was updated
- Formio redraw was removed in `convertFormLinksToOpenInNewTabs`
=> web docker files were updated - form validation render issue was fixed

forms-flow-web/src/components/Draft/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/View.js, forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js, forms-flow-web/src/helper/PrintPDF.js, forms-flow-web/src/services/PdfService.js
DGJ-640 Add the "Print As PDF" button on the application edit, Draft edit, and Task tab.
- use existing exportToPDF() function to download PDF file.
- Add **ID** on div which is a form container to print Form as PDF.
=> DGJ-640 add Print as PDF button on Draft, Application and Task tabs

forms-flow-bpm/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, forms-flow-web/src/apiManager/services/bpmTaskServices.js, forms-flow-web/src/components/ServiceFlow/constants/taskConstants.js
DGJ-636 Hide the Senior Leadership Review form from the task tab
Added constant that helps to filter tasks. It must be added as a description on the Camunda process "User Tasks".
N/A
=> DGJ-636 Hide senior leadership review form the task list tab

forms-flow-web/src/services/PdfService.js
DGJ-640 Fixed CSS does not display and content breaks in the PDF pages.
Scale: 2 try to scale up the image for the PDF. That makes some CSS not apply issues, and for edge browsers, it breaks content between 2 pages.
I have downgraded the scale to 1. As the default value is window.devicePixelRatio that makes a bit different based on the user's browser window.
N/A
=> DGJ-640-fix-css-issue-in-export-pdf

forms-flow-web/src/styles.scss
- Changed the border color of select dropdowns to match text fields
- Changed the sizing of select dropdowns to match text fields
Before: 
After:
=> DGJ-686 Style border of select dropdowns same as text fields

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
Remove the back button and "print as PDF" duplicate from the task tab.
Added Prop to hide and show Print As PDF and back button on the application edit page.
=> Hide Print as PDF and back button from the form in task tab

forms-flow-web/src/components/Form/FormOperations/FormOperations.js, forms-flow-web/src/containers/styles.scss
DGJ-709 Add button to draft forms in forms tab tabl
Add redirect to /draft page button and enable it for client and reviewer roles in the formOperations file.
=> DGJ-709 Add button to draft forms in forms tab table

forms-flow-web/src/components/Form/Item/View.js, forms-flow-web/src/components/ServiceFlow/constants/customEventTypes.js
Added script in SL review that ensures the form must not save if employee name is not provided.
- Added Hidden field in SL review form and set a default value to true, If the name is not selected then it will change to false and that will stop auto-save.
- If the name is not selected and someone is trying to save by clicking on the button, it will show a toast message, please check the attached screenshot for reference.
=> DGJ-722 SL Review: Don't save if there is no Employee Name in the form

forms-flow-web/src/components/Draft/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/View.js, forms-flow-web/src/components/Form/Item/View.js, forms-flow-web/src/helper/formUtils.js
This PR fixes the issue of forms' links were not open in new tabs. #742 
- Redraw the form after changes to the form `HTML` strings to make sure converted links are properly rendered
- Ensure that the redraw only runs once otherwise, it will clear forms validations and some other side-effects
=> form is redraw after links conversion and make sure it runs once

.github/workflows/forms-flow-web-cd.yml
Allow web build to run using a manual trigger
=> DGJ-723-allow-build-to-run-manually

forms-flow-web/src/components/Footer/Footer.js
DGJ-732 Contact us in the footer goes to GDX and should go to DJ mailbox
change redirect link to mailto:<DJ email>
=> DGJ-732 Contact us in the footer goes to GDX and should go to DJ mailbox

forms-flow-web/src/components/Footer/Footer.js, forms-flow-web/src/styles.scss
DGJ-765 apply new css for data-grid
DGJ-732 contact us should open mail for DJ email.
- Add a new stylesheet that overrides data-grid CSS. (check out screenshots)
- Considering that we will add it as same, I have added flex with 2 inputs in a row if the width is >768px.
- Change contact link to mailto: {DJ email}
Single
After adding duplicate details.
I did keep the "add button" as primary, can override it's CSS and make it look like a link. check below screenshot.
=> Dgj 765 apply new css for data-grid

forms-flow-web/src/components/Draft/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Success/SuccessPage.js, forms-flow-web/src/components/Form/Item/View.js, forms-flow-web/src/constants/successTypes.js
DGJ-794 Change 1.10 form success page content based on PSA or LDB
- Pass the submission parameter in the form redirect, which will help to identify the success page based on submission data.
- Added content for the PSA and LDB conditions for article 1.10 form.
NA
=> DGJ-794 Change 1.10 form success page content based on PSA or LDB

forms-flow-web/src/services/PdfService.js
DGJ-811 Hide Content that has .hidden-in-print and formio button classes.
- Set visibility for the floating and formio buttons.
- Set display property for the content that has class .hidden-in-print. If the content has no visibility, it will occupy space and put a blank page and block in PDF, hence hiding it.
NA
=> DGJ-811 Hide content that has .hidden-in-print class and formio button

forms-flow-web/src/services/PdfService.js
Checked radio button disappear on download pdf button click
Capture all checked radio buttons and mark them checked again after PDF download.
=> DGJ-892 Fix radio button disappear on download pdf button click

forms-flow-web/src/components/Draft/Edit.js
Draft saved with previous ID on an unmount event.
- Stop saved on unmount event on draft edit page
- Revert fetching peoplesoft data on draft page
Issue seems legacy, draftSubmission has latest value, but for UNMOUNT event it fire with previous values.
=> Revert peoplesoft latest data and ignore UNMOUNT event on draft page

scripts/idir-username-migration.js
This PR restores the IDIR users' drafts, submissions, and tasks after their usernames were changed due to the BCeID+BCSC integration. #886 
This PR first identified the tables and columns in the `webapi` and `Camunda` databases that can effectively restore the already saved/in-progress/submitted drafts/submissions/Camunda tasks and then do the IDIR username migration through a script.
- A script directory was added to the repo to store the migration script. It can be used for similar scripts in the future.
- Migration script updates four tables in two databases
- `webapi`
- `application`: Will restore the drafts and submitted applications.
- `application_audit`: Will restore the submitted application in different states (audit). This might be useful in analytics in the future.
- `Camunda` …
=> DGJ_886-idir-username-migration

deployment/openshift/Databases/redis-cluster.dc.yaml, forms-flow-analytics/docker-compose.yml
This PR updates Redash and Redis versions to the latest compatible versions. #849 
- Redash was updated to its latest version in docker-compose. It already was updated in the Openshift and all the envs.
- Redis was updated in its Openshift config and docker-compose files to the latest compatible version. Already updated in the Openshift and all the envs.
=> DGJ_849-redash_and_redis_updated

forms-flow-web/src/components/Form/Item/Submission/Success/SuccessPage.js
Added new bullet to 1.10 success pages for LDB and PSA as per DJ935.
Added new success page list item for 
COMPLAINT_INTAKE_FORM_1_10_NOEMAIL,
COMPLAINT_INTAKE_FORM_1_10_LDB,
COMPLAINT_INTAKE_FORM_1_10
In the “Before you submit” section of a PSA complaint, add a new (second) bullet that reads: “PSA will assess your complaint and contact you regarding the process and timeline for next steps”.  
For an LDB complaint, the bullet should read: “LDB will assess your complaint and contact you regarding the process and timeline for next steps.”
=> DJ935 Add final success page updates

docs/AddUserAndAssignGroup/index.md, forms-flow-api/src/formsflow_api/resources/employeeData.py, forms-flow-api/src/formsflow_api/schemas/__init__.py, forms-flow-api/src/formsflow_api/schemas/keycloak_admin.py, forms-flow-api/src/formsflow_api/services/__init__.py, forms-flow-api/src/formsflow_api/services/external/keycloak.py, forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py, forms-flow-api/src/formsflow_api/services/keycloak_service.py
- Added an API to automation add new users and assign provided group. 
- If user is already exist with same email/idp then only assign group.
- Added webapi that accept user(first & last name, email and idp) object as array and group name.
- API will return same user object response with additional details like "user_id", "success" and "updated" with group to help issuer(developer or designer user) save response or display(If we integrate it with frontend).
- Only "Form Designer" are able to call this API.
I'll add documentation and sample data for the API. As it will be handle by developer only(unless we add frontend for the same)
It will help to trigger the API from local script with designer token or from postman app. It will not required developer to collect keycloak configuration as …
=> DGJ-964 an API to add user in Keycloak and assign group

scripts/keycloak-duplicate-account-fix.js
This PR resolves the issue of duplicate Keycloak users for managers in PROD as well as migrating the legacy users in Keycloak to the new username. #965
=> DGJ_965-duplicate-keycloak-accounts-issue

docs/forms.md, forms-flow-web/src/components/Draft/Edit.js, forms-flow-web/src/components/Draft/EditDraft.js
Retrive User's latest details in Draft form, if Form has enable that option.
- Retrive user's details if they reload draft edit page.
- Replace latest value from user's object if form fields are disabled and form has hidden field "enableDraftDefault" with value 
Added document on how to enable this requirements.
=> Enable default user data in draft edit with 2 conditions

forms-flow-api/src/formsflow_api/resources/influenzaWorksite.py, forms-flow-api/src/formsflow_api/services/influenza_service.py
This PR Adds two endpoints to webApi that allow a form designer to get worksites-related data from the warehouse.
- `influenza/worksites_ministries` endpoint was added to fetch worksites-ministry-related data, supporting filter and select params
- `influenza/worksites_registrations`  was added to fetch worksites-registrations-related data, supporting filter and select params
=> DGJ_1000-add-ministry-registration-endpoints

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/index.js, forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js, forms-flow-web/src/constants/constants.js
This PR fixes the issue of formio wasn't reliably know whether the submission is opened on the Edit Submission page or Review Submission page. This was required to display some form components depending on where that page is loaded.
- A new status `editSubmissionPage` with two values was added to the form submission object.
- `ServiceFlowTaskDetails` was improved to only load the edit submission component of submission data is loaded.
=> DGJ_906-improve-edit-page-validation

forms-flow-api-utils/src/formsflow_api_utils/utils/constants.py, forms-flow-api/src/formsflow_api/resources/employeeData.py
This PR changes `sl-review-adm` mapped role name from `employee-serach` to the same name -- making it consistent with other group-role mapping names. #1159
=> DGJ_1159--sl_review_role_name_change

forms-flow-web/src/services/PdfService.js
DGJ-1216 Senior Leader Name is cut off in the PDF generated online
Added script that make block visible if someone click on print button.
NA
=> DGJ-1216 SL Name is cut off in PDF generated online

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/model/CrmChannel.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/model/CrmContentType.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/model/CrmThread.java
DGJ-1190 Added Mat-Pat form fields in CRM ticket thread
- Added Channel and content type to handle CRM thread configuration
- Added thread with HTML/CSS channel and content type as HTML/TEXT
- Thread text will be calculate on form itself with hidden field `threadText`
- `threadText` should be pass as input param in workflow when invoking crmDelegate.
NA
=> DGJ-1190 Mat-Pat CRM ticket thread integration

forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py, forms-flow-api-utils/src/formsflow_api_utils/utils/constants.py, forms-flow-api-utils/src/formsflow_api_utils/utils/enums.py, forms-flow-api-utils/src/formsflow_api_utils/utils/util.py, forms-flow-api/src/formsflow_api/resources/application.py, forms-flow-api/src/formsflow_api/resources/formio.py, forms-flow-forms/formsflow-template.json, forms-flow-web/src/components/Application/List.js, forms-flow-web/src/components/Application/table.js, forms-flow-web/src/constants/constants.js
DGJ-1279 Allow group of SL review admin to view and print submissions
- Added code that can extend for view only on WEB
- Added sl-review-admin group and key to allow user to fetch application list
- Added formio roles for sl-review-admin in utils.
- Added sl-review-admin in formio formflow-template.json file
NA
=> DGJ-1279 SL admin group with view all submission rights

forms-flow-web/src/services/PdfService.js
DGJ-1291 in edit form, Print to PDF is trim text and show only 1st line
- Select all text area field and hide at the time of print.
- Pull text from text area and add in DIV
- Remove temp divs for text and Show textarea again.
NA
=> DGJ-1291 in edit form, Print to PDF is trim text and show only 1st line

forms-flow-web/src/formComponents/CurrencyComponent/index.js
This PR fixed the issue with the `DGJCurrencyComponent` popup. 
- Loaded children element was changed
The fixed was kinely provided by Bhumin :)
=> Currency calculator popup was fixed

forms-flow-web/src/styles.scss
Fixed spacing issues for alert banners with text that does not fully span a line.
Removed center alignment for alert icons so that they align with first line of associated paragraph text.
=> DGJ-1294 Fix alert banner alignment

forms-flow-web/src/components/Application/List.js, forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/index.js, forms-flow-web/src/constants/applicationConstants.js, forms-flow-web/src/constants/formConstants.js, forms-flow-web/src/helper/access.js, forms-flow-web/src/helper/helper.js
This PR adds a new form edit access system that allows each form to control which status should be allowed for user access. #895 
- Replacing the list of status that supports editing, with a new form-mapper that allow each form to control its status for edit submission access
- Updated the components that deal with edit submission to work with the new access system.
- Added new status to the Mat/Pat form: (`NEW`, `APPROVED` and `DENIED`)
- Apart from this PR, the mat/pat form was updated to support the new status and its workflow now has `status` as part of the task name displayed in the list under the `/task` page.
=> DGJ_895-mat_pat-new-status

forms-flow-web/src/components/Draft/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js, forms-flow-web/src/components/Form/Item/Submission/Item/View.js, forms-flow-web/src/components/Form/Item/View.js, forms-flow-web/src/helper/formUtils.js
This PR (#1349) improves the existing function that converts all the form's links to open in new tabs. Instead of modifying the live form after it's been rendered, it changes the links before the form is rendered (changes the static form). This will ensure all the links even those that are conditionally rendered in the line form (used to miss the _blank attribute) are opening in new tabs.
One improvement over my approach would be to modify the form right after/before added to the state. I wasn't able to find the right place where Redux adds form to the app state and instead changes the form state in each component (e.g., view, draft, edit submission etc). Please let me know if you know how to change the form there so we modify the form in one place instead of all view/edit/draft files.
=> DGJ_1349-open-links-in-new-tabs

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/model/CrmIncidentPatchRequest.java
DGJ-1381 send an email to supervisor when CRM ticket update
- Call `/incidentReponse` endpoint to update CRM incident with send email configuration
- Keeping existing update flow as it is, because `/incidentReponse` does not support status and contact param
NA
=> DGJ-1381 send an email to supervisor when CRM ticket update

forms-flow-web/src/styles.scss
- The previous bg color is white. Changing this to be same as warning yellow color.
- Also need to add the class to the form.
=> DGJ-1414 | add warning bg color

forms-flow-api/src/formsflow_api/models/draft.py, forms-flow-api/src/formsflow_api/resources/application.py, forms-flow-api/src/formsflow_api/resources/draft.py, forms-flow-api/src/formsflow_api/services/application.py, forms-flow-api/src/formsflow_api/services/draft.py
This PR improves the initial submission error handling and ensure no unnecessary data is created and draft is preserved  when submission failed because of an issue in Camunda and workflow start. Ticket #1484 
- webApi: Draft resource, service, and model were updated to handle the Camunda workflow start issue.
- webApi: Application resource and service were updated to address the Camunda workflow start issue.
- webApi: The original user draft is preserved in case of a Camunda workflow start issue.
- webApi: The application is reverted back to draft status in case of a Camunda workflow start issue.
- webApi: Formio submission is deleted in case of a Camunda workflow start issue.
=> DGJ_1484-improve-initial-submission-error-handling

docs/upgrading.md
This PR adds the long overdue documentation for Formio for v5.10 and onwards.
=> Formio upgrade documentation

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java
- add file name from the form to crm
- From the Form (This required change from the form):
```js
// This is fixed. ignore this one.
const prefix = "MatPar";
const ext = ".pdf";
const timestamp = new Date().toISOString();
let fullName = data["name_2"] || data["name"];
fullName = fullName.split(" ").join("_");
const result = [prefix, fullName, timestamp, ext].join("_");
value = result;
```
- New version
```js
const prefix = "MatPar";
const ext = ".pdf";
const timestamp = new Date().toISOString();
let fullName = data["name_2"] || data["name"];
fullName = fullName.split(" ").join("_");
const result = [prefix, fullName, timestamp].join("_") + ext;
value = result;
```
- Edit JSON
```json
{
"label": "crmMatPatAttachmentFileNameField",
"defaultValue": "attachment.pdf",
"calculateValue": "const …
```
=> DGJ-1512-attachment file name

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java
- root cause: missed the `execution` variable
=> DGJ-1512-Hotfix | Image build failure

forms-flow-web/src/components/Form/Item/Submission/Success/SuccessPage.js
- Removed the list style in Denied Page.
- Simply remove `ol` and `li` tags.
From Old:
To New:
=> DGJ-1572 | remove li tag in Denied Page

forms-flow-web/src/styles.scss
Removes margin for hidden alert components so that they do not take create excess whitespace.
=> Remove margin for hidden alert components

forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
- Remove unnecessary console.warn
- After digging the code for a while, `console.warn` is happening in formio source code `getForm`, so nothing we can do but put the `console.warn` to be empty function in that scope, not effecting the global scope. I believe this is the best way for this case.
https://github.com/formio/react/blob/master/src/modules/form/actions.js
=> DGJ-1501 | disable console.warn in the function

forms-flow-web/src/apiManager/services/bpmTaskServices.js, forms-flow-web/src/constants/userContants.js
DGJ-1612 Filter only assigned task for formflow-client role
- Added CLIENT role in filter for assignee user name on service task list API call.
NA
NA
=> DGJ-1612 Filter only assigned task for formflow-client role

forms-flow-web/src/constants/formConstants.js
- Fix the constant text and then it will show "Edit" button on submitted page.
- This line did include cold-flu-admin to show all applications on submitted page, so we don't need to add more.
=> DGJ-1652 | Cold/Flu | Admin user can edit on "submitted" page.

forms-flow-web/package.json, forms-flow-web/src/customHooks/useSnowPlow.js
Had the meeting with Dan and Warren.
There are 2 issue we need to resolve:
Refer to comments on zenhub: https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1352
- Bug: duplicate call at beginning when page load at first time.
Fixed: no duplicate call.
- Enhancement: add 'refreshLinkClickTracking' , then snowplow will know user is clinking on the "link". can use gov page to know what is correct behaviour.
Ref: https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/tracking-events/link-click/#refresh-link-click-tracking
Fixed: now you can see purple color, meaning user click on the `<a />` tag.
=> DGJ-1352 | Snowplow further fix | fix duplicate call; add linkTracking

forms-flow-idm/keycloak/themes/bcgov/login/template.ftl, forms-flow-web/src/components/Application/List.js, forms-flow-web/src/components/Draft/List.js, forms-flow-web/src/components/Form/FormOperations/FormOperations.js, forms-flow-web/src/containers/NavBar.jsx, forms-flow-web/src/styles.scss
Added guest login detail on keycloak.
Hide draft and application page from menu, list and set redirect on /form for guest user.
- Added user name **anonymous_guest** in keycloak with role **forms-flow-client** and **anonymous**.
- From the existing const use **anonymous_user** and add conditions on draft, application and form page to hide unnecessary content.
NA
NA
=> DGJ-1789 guest login hide draft and application pages

forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
- To always show submission loading
- I found that after fetching, `isTaskLoading` become `true`, and then will show 3-ball loader.
- so we add one more condition `!isCustomFormSubmissionLoading`
=> DGJ-1785 | always showing submission loading

forms-flow-web/src/components/Form/Item/Submission/Success/SuccessPage.js
Just removed periods to standardize the ERIP success page.
=> Update ERIP success page content

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/model/CrmIncidentPostRequest.java
Select the category based on ID instead of name if provided in the form. Some end categories are similar under different main categories. For example, `Maternity Leave` falls under both "`Maternity, Parental, and Adoption Leave`" and "`T2 Payroll (Transaction)`". In this case, we need the ID of the selected category.
- When we provide `crmCategoryLookupId` in the form, it will prepare a POST request for CRM incident with the ID lookup.
- If it is not provided, it will continue using the `crmCategoryLookupName` field to prepare the POST CRM incident request.
- Ignore product and assignTo at time of CRM update request, It is enabled for all forms for now.
Using an ID to lookup a category is not advisable and should be used only in certain cases. Along with crmCategoryLookupId, one must …
=> Dgj 1759 crm category update based on id and not name

forms-flow-web/src/styles.scss
Align wizard buttons so they are not bunched together.
Move "next" button to the right if it is the only child.
This will enable us to utilize the built in wizard nav buttons for the coi instead of custom, allowing navigation in view only mode.
=> Enhance button alignment in wizard navigation for improved layout

forms-flow-web/src/styles.scss
Fix to align the wizard nav button on the first page, when there is only a single child (the first page next button).
=> Refactor wizard navigation styles for improved button alignment

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CrmDelegate.java
Added flag to prevent attachment in crm ticket.
The code checks for a process variable named generateCrmAttachment in camunda.
If this variable is set to false (as a Boolean or a String "false"), attachment generation is skipped.
If the variable is not set, the default is true and attachments are generated.
=> Add flag to control CRM attachment generation in CrmDelegate
